<?php

use LightSaml\Credential\X509Certificate;
use Drupal\Component\Render\MarkupInterface;

/**
 * Outputs readable x509 certificate info.
 *
 * @param \LightSaml\Credential\X509Certificate $cert
 *
 * @return \Drupal\Component\Render\MarkupInterface|null
 * @throws \Exception
 */
function _light_saml_idp_cert_info(X509Certificate $cert): ?MarkupInterface {
  if ($cert->getInfo() !== null) {
    /** @var \Drupal\Core\Datetime\DateFormatter $dateFormatter */
    $dateFormatter = \Drupal::service('date.formatter');
    /** @var \Drupal\Core\Render\Renderer $renderer */
    $renderer = \Drupal::service('renderer');

    $info = [
      '#theme' => 'certificate_info',
      '#name' => $cert->getName(),
      '#issuer' => implode('/ ', $cert->getIssuer()),
      '#valid_from' => $dateFormatter->format($cert->getValidFromTimestamp(), 'short'),
      '#valid_to' => $dateFormatter->format($cert->getValidToTimestamp(), 'short'),
    ];
    return $renderer->render($info);
  }
  return null;
}

/**
 * Implements hook_theme().
 */
function light_saml_idp_theme() {
  return [
    'certificate_info' => [
      'variables' => [
        'name' => NULL,
        'issuer' => NULL,
        'valid_from' => NULL,
        'valid_to' => NULL,
      ],
    ],
    'metadata' => [
      'variables' => [
        'xml_content' => NULL,
      ]
    ]
  ];
}
