light_saml_idp.settings:
  type: config_object
  label: 'Settings'
  mapping:
    contact:
      type: mapping
      label: 'Contact'
      mapping:
        support:
          type: mapping
          label: 'Support'
          mapping:
            name:
              type: string
              label: 'Name'
            email:
              type: email
              label: 'Email'
    organization:
      type: mapping
      label: 'Organization'
      mapping:
        name:
          type: string
          label: 'Name'
          description: 'This is a short name for the organization'
        display_name:
          type: string
          label: 'Display Name'
          description: 'This is a long name for the organization'
        url:
          type: string
          label: 'URL'
          description: 'This is a URL for the organization'
    security:
      type: mapping
      label: 'Security'
      mapping:
        signing:
          type: mapping
          label: 'Signing'
          description: 'Signing security configuration'
          mapping:
            cert_location:
              type: string
              label: 'Certificate Location'
              description: 'The location of the x.509 certificate file on the server. This must be a location that PHP can read.'
            key_location:
              type: string
              label: 'Key Location'
              description: 'The location of the x.509 key file on the server. This must be a location that PHP can read.'
    entity_id:
      type: string
      label: 'Entity ID'
      description: 'The unique identifier that the IdP intentifies this site for the Relying Party Trust.'
    debug:
      type: boolean
      label: 'Debug Mode'

light_saml_idp.sp.*:
  type: config_entity
  label: 'SAML Service Provider'
  mapping:
    label:
      type: label
      label: 'Name'
      translatable: false
    id:
      type: string
      label: 'Machine-readable name'
    entityId:
      type: string
      label: 'Entity ID'
      description: 'The entityID, this may sometimes be a URL.'
    acsUrl:
      type: string
      label: 'Assertion Consumer Service URL'
      description: 'Assertion Consumer Service URL of the Service Provider.'
    signingMessage:
      type: boolean
      label: 'Sign message'
    signingAssertion:
      type: boolean
      label: 'Sign assertion'
    signingCertificate:
      type: sequence
      label: 'x.509 Signing certificate'
      description: 'Enter the signing certificate provided by the SP.'
      sequence:
        type: string
    signingMethod:
      type: string
      label: 'Signing method'
    encryptionAssertion:
      type: boolean
      label: 'Assertion encryption'
    encryptionCertificate:
      type: sequence
      label: 'x.509 Encryption certificate'
      description: 'Enter the encryption certificate provided by the SP.'
      sequence:
        type: string
    encryptionMethod:
      type: string
      label: 'Encryption method'
